name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Upload production-ready static files
        uses: actions/upload-pages-artifact@v3
        with:
          # قمنا بتغيير هذا المسار ليتوافق مع معظم مشاريع React
          path: ./frontend/build 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
